modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="mistterysmod"
version="1.0.0"
displayName="Misttery's Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="MARA2, MCreator"

[[dependencies.mistterysmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



